import { Member } from "@src/types";

export const members: Member[] = [
  {
    nickname: "たろう",
    realName: "長澤太郎",
    bio: "Kotlinの人だけど、いろいろやってるよ！",
    avatarSrc: "/avatars/taro.jpg",
    sources: ["https://taro.hatenablog.jp/feed"],
    includeUrlRegex: "taro.hatenablog.jp",
    twitterUsername: "ngsw_taro",
    githubUsername: "ngsw_taro",
    websiteUrl: "https://taro.hatenablog.jp/",
  },
  {
    nickname: "jimbo",
    realName: "神保嘉秀",
    bio: "大阪からリモートワークしてます",
    avatarSrc:
      "https://pbs.twimg.com/profile_images/951461895231348736/wnfNYZpX.png",
    sources: ["https://jmblog.jp/atom.xml", "https://qiita.com/jimbo/feed", "https://zenn.dev/jimbo/feed"],
    twitterUsername: "jmblog",
    githubUsername: "jmblog",
    websiteUrl: "https://jmblog.jp",
  },
  {
    nickname: "たつろろ",
    realName: "中村達郎",
    bio: "Webフロントエンドが得意です。福岡在住",
    avatarSrc: "/avatars/tatsuroro.jpg",
    sources: ["https://tatsuroro.hateblo.jp/feed"],
    includeUrlRegex: "tatsuroro.hateblo.jp",
    twitterUsername: "tatsuroro",
    githubUsername: "tatsuroro",
    websiteUrl: "https://tatsuroro.hateblo.jp/",
  },
  {
    nickname: "しらじ",
    realName: "磯貝佳典",
    bio: "家紋アイコンしらじです。フロント、バックエンドやってます",
    avatarSrc: "/avatars/shiraji.png",
    sources: ["https://shiraji.hatenablog.com/feed"],
    includeUrlRegex: "shiraji.hatenablog.com",
    twitterUsername: "shiraj_i",
    githubUsername: "shiraji",
    websiteUrl: "https://shiraji.hatenablog.com",
  },
  {
    nickname: "しきち",
    realName: "敷地琢也",
    bio: "フロント、バックエンド、スクラムマスターなんでもやります。最近はプロダクトオーナーやってます",
    avatarSrc: "/avatars/shikichee.jpg",
    sources: ["https://note.com/shikichee/rss"],
    includeUrlRegex: "note.com/shikichee",
    twitterUsername: "shikichee",
    githubUsername: "shikichee",
    websiteUrl: "https://note.com/shikichee",
  },
  {
    nickname: "めぐ",
    realName: "目黒博隆",
    bio: "4児の父親エンジニア。フロント・バックエンド担当してます。",
    avatarSrc: "/avatars/megu.jpg",
    sources: ["https://qiita.com/maguhiro/feed"],
    twitterUsername: "maguhiro",
    githubUsername: "maguhiro",
    websiteUrl: "https://qiita.com/maguhiro",
  },
  {
    nickname: "quvo",
    realName: "久保恒太",
    bio: "共同代表。元エンジニア兼なんでも屋",
    avatarSrc: "/avatars/quvo.jpg",
    sources: ["https://note.com/quvo_ub/rss"],
    includeUrlRegex: "note.com/quvo_ub",
    twitterUsername: "quvo_ubie",
    githubUsername: "quvo",
    websiteUrl: "https://note.com/quvo_ub",
  },
  {
    nickname: "soup",
    realName: "souppower",
    bio: "強い犬",
    avatarSrc: "/avatars/soup.png",
    sources: ["https://qiita.com/souppower/feed"],
    includeUrlRegex: "https://qiita.com/souppower",
    twitterUsername: "souppower",
    githubUsername: "souppower",
    websiteUrl: "https://qiita.com/souppower",
  },
  {
    nickname: "itkq",
    realName: "Takuya Kosugiyama",
    bio: "YAML難しい",
    avatarSrc: "/avatars/itkq.png",
    sources: ["https://zenn.dev/itkq/feed"],
    twitterUsername: "itkq",
    githubUsername: "itkq",
    websiteUrl: "https://itkq.jp/about/",
  },
  {
    nickname: "h13i32maru",
    realName: "Ryo Maruyama",
    bio: "JasperとかTrickleとか作ってる",
    avatarSrc: "/avatars/h13i32maru.jpg",
    sources: ["https://blog.h13i32maru.jp/feed"],
    twitterUsername: "h13i32maru",
    githubUsername: "h13i32maru",
    websiteUrl: "https://h13i32maru.jp",
  },
].sort((a, b) => (a.nickname < b.nickname ? -1 : 1));
